### ISSUE TITLE
Inconsistent access to Calculate and Analysis Page for unauthenticated users

### ISSUE THREAD

**Issue by eric-mh** [codeday-labs/wej-tech#18]
Users not logged in can currently submit an image in Calculate, but cannot view Analysis results.

The web app should either:
* Prevent unauthenticated users from submitting images to calculate with
* Allow unauthenticated users to view analysis results.

**Comment by Wail-Mohammed** [comment]
Resolved, now Analysis page displays results for unathenticated users (guest) and for authenticated users.
