### ISSUE TITLE
"Carbon Absorbed" statistic in analysis results isn't shown 

### ISSUE THREAD

**Issue by eric-mh** [codeday-labs/wej-tech#19]
In Analysis page, under the statistic "Carbon Absorbed," the stat number isn't shown when it should. The variable in the frontend needs to be changed, in order to display the stats.

**Comment by Wail-Mohammed** [comment]
Fixed and tested. The website calculations tool should now display carbon absorption rate. The changes are made and pushed to jericho-calculation-result
