### ISSUE TITLE
Unnecessary "Subtle Text" descriptions in the Analysis results page

### ISSUE THREAD

**Issue by eric-mh** [codeday-labs/wej-tech#22]
In Analysis page, under every statistic there's text saying "Subtle Text." It needs to be removed if there's nothing to say there.

**Comment by Wail-Mohammed** [comment]
Resolved by removing "Subtle Text" and replacing it with Disclaimer: "These values are only an estimate and not meant to be used scientifically" at the end of the Analysis page.
