### ISSUE TITLE
Calculate page has a "debugger" text in a dark grey box.

### ISSUE THREAD

**Issue by eric-mh** [codeday-labs/wej-tech#24]
In the Calculate page, there's still the frontend "debugger" text in a dark grey box.

This should be removed.

**Comment by tranngocsongtruc** [comment]
Resolved in https://github.com/codeday-labs/wej-tech/commit/0534be867d1eaaf18d90f611e1edb7736dda2499

**Comment by tranngocsongtruc** [comment]
Re-resolved in https://github.com/codeday-labs/wej-tech/commit/a8223468bc015ac9307f7571a7513744ac4c36e4 
I re-added the progress bar into the ImageUpload.js file after accidentally deleting it which was in the debugger dark grey box.
